apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ej03rlmzn-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ej03rlmzn-go 
  name: ej03rlmzn-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ej03rlmzn-go 
